db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1083898997,
    est_primer_apellido: "GOMEZ",
    est_segundo_apellido: "GALLARDO",
    est_primer_nombre: "BRIGITH",
    est_segundo_nombre: "DAYANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Brigith Dayana Gomez Gallardo.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1080933858,
    est_primer_apellido: "RENGIFO",
    est_segundo_apellido: "MURCIA",
    est_primer_nombre: "JHON",
    est_segundo_nombre: "ALEJANDRO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - John Alejandro Rengifo Murcia.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1029988516,
    est_primer_apellido: "LUGO",
    est_segundo_apellido: "CESPEDES",
    est_primer_nombre: "MONICA",
    est_segundo_nombre: "MARIA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Monica Maria Lugo Cespedes.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1079536132,
    est_primer_apellido: "BECERRA",
    est_segundo_apellido: "SAPUY",
    est_primer_nombre: "HERMES",
    est_segundo_nombre: "DAVID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Hermes David Becerra Sapuy.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1084333984,
    est_primer_apellido: "MANRIQUE",
    est_segundo_apellido: "MURCIA",
    est_primer_nombre: "DANIELA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Daniela Manrique Murcia.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1144625322,
    est_primer_apellido: "GUEVARA",
    est_segundo_apellido: "ANACONA",
    est_primer_nombre: "KAROL",
    est_segundo_nombre: "YULIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Karol Yuliana Guevara Anacona.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEXTO",
    est_sector: "OFICIAL",
    est_grupo: 601,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1083882731,
    est_primer_apellido: "CASTRO",
    est_segundo_apellido: "LOPEZ",
    est_primer_nombre: "LUISA",
    est_segundo_nombre: "FERNANDA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Luisa Fernanda Castro Lopez.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEXTO",
    est_sector: "OFICIAL",
    est_grupo: 601,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1083881137,
    est_primer_apellido: "GUZMAN",
    est_segundo_apellido: "GIRON",
    est_primer_nombre: "DEINY",
    est_segundo_nombre: "LICETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Deiny Liceth Guzman Giron.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEXTO",
    est_sector: "OFICIAL",
    est_grupo: 602,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1083880617,
    est_primer_apellido: "FLOREZ",
    est_segundo_apellido: "CHITO",
    est_primer_nombre: "WENDY",
    est_segundo_nombre: "KATERINE",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Wendy Katerine Florez Chito.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEXTO",
    est_sector: "OFICIAL",
    est_grupo: 602,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1080932299,
    est_primer_apellido: "RAMOS",
    est_segundo_apellido: "TRIVINO",
    est_primer_nombre: "DANNA",
    est_segundo_nombre: "SOFIA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Danna Sofía Ramos Triviño.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEPTIMO",
    est_sector: "OFICIAL",
    est_grupo: 701,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1028400945,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "GABRIELA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Gabriela Gutiérrez Muñoz.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEPTIMO",
    est_sector: "OFICIAL",
    est_grupo: 701,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1079535175,
    est_primer_apellido: "ALDANA",
    est_segundo_apellido: "GARZON",
    est_primer_nombre: "FAIVER",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Faiver Aldana Garzón.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEPTIMO",
    est_sector: "OFICIAL",
    est_grupo: 702,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1083876703,
    est_primer_apellido: "CASTAÑEDA",
    est_segundo_apellido: "NIETO",
    est_primer_nombre: "ANGELA",
    est_segundo_nombre: "ROCIO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Angela Rocío Castañeda Nieto.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "SEPTIMO",
    est_sector: "OFICIAL",
    est_grupo: 702,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1087191962,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "OSPITIA",
    est_primer_nombre: "BREINER",
    est_segundo_nombre: "ESTIBEN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Breiner Stiven Muñoz Ospitia.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "OCTAVO",
    est_sector: "OFICIAL",
    est_grupo: 801,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1080931206,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "HERRERA",
    est_primer_nombre: "EDNA",
    est_segundo_nombre: "LIZETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Edna Lizeth Gutiérrez.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "OCTAVO",
    est_sector: "OFICIAL",
    est_grupo: 801,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "RC",
    est_doc: 1080930822,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "STERLING",
    est_primer_nombre: "LINA",
    est_segundo_nombre: "MARCELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Lina Marcela Garzón Sterling.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "NOVENO",
    est_sector: "OFICIAL",
    est_grupo: 901,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1083866526,
    est_primer_apellido: "ROMERO",
    est_segundo_apellido: "ORDOÑEZ",
    est_primer_nombre: "DANA",
    est_segundo_nombre: "YERALDIN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Danna Geraldin Romero Ordoñez.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "NOVENO",
    est_sector: "OFICIAL",
    est_grupo: 901,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1079534274,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "COLLAZOS",
    est_primer_nombre: "CARLOS",
    est_segundo_nombre: "ALBERTO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Carlos Alberto Muñoz Collazoz.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "DÉCIMO",
    est_sector: "OFICIAL",
    est_grupo: 1001,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1080930366,
    est_primer_apellido: "YATE",
    est_segundo_apellido: "ROMERO",
    est_primer_nombre: "CAREN",
    est_segundo_nombre: "YULISA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Caren Yulisa Yate Romero.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "DÉCIMO",
    est_sector: "OFICIAL",
    est_grupo: 1001,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1004208825,
    est_primer_apellido: "STERLING",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "DANIEL",
    est_segundo_nombre: "EDUARDO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Daniel Eduardo Sterling Calderón.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1004209893,
    est_primer_apellido: "GUZMAN",
    est_segundo_apellido: "GUTIERREZ",
    est_primer_nombre: "NATALIA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 1,
    est_foto: "1 - Natalia Guzmán Gutiérrez.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1004208693,
    est_primer_apellido: "ROJAS",
    est_segundo_apellido: "MEDINA",
    est_primer_nombre: "EVELIN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_estudiantil",
    est_num_tarjeton: 2,
    est_foto: "2 - Evelin Rojas Medina.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1007462630,
    est_primer_apellido: "GUEVARA",
    est_segundo_apellido: "DIAZ",
    est_primer_nombre: "CAREN",
    est_segundo_nombre: "YULIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_directivo",
    est_num_tarjeton: 1,
    est_foto: "1 - Caren Yuliana Guevara Díaz.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1006028999,
    est_primer_apellido: "OLAYA",
    est_segundo_apellido: "LOZANO",
    est_primer_nombre: "YHONATAN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "representante_consejo_directivo",
    est_num_tarjeton: 2,
    est_foto: "2 - Jhonatan Olaya Lozano.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1004208316,
    est_primer_apellido: "BURBANO",
    est_segundo_apellido: "RUIZ",
    est_primer_nombre: "KAREN",
    est_segundo_nombre: "JULIETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "personero",
    est_num_tarjeton: 1,
    est_foto: "1 - Karen Jhulieth Burbano Ruiz.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1004208680,
    est_primer_apellido: "CUELLAR",
    est_segundo_apellido: "SANTIAGO",
    est_primer_nombre: "YOLIMA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "personero",
    est_num_tarjeton: 2,
    est_foto: "2 - Yolima Cuéllar Santiago.jpg"
});
db.candidatos.insert({
    est_anio: 2019,
    est_secretaria: "TIMANÁ",
    est_dane_ie:  241807000079,
    est_nombre_ie:  "IE CASCAJAL",
    est_dane_sede: 24180700007901,
    est_nombre_sede: "CASCAJAL",
    est_jornada: "ÚNICA",
    est_calendario: "A",
    est_grado: "ONCE",
    est_sector: "OFICIAL",
    est_grupo: 1101,
    est_modelo_educativo: "EDUCACIÓN TRADICIONAL",
    est_tipo_identificacion: "TI",
    est_doc: 1007361176,
    est_primer_apellido: "SILVA",
    est_segundo_apellido: "PENAGOS",
    est_primer_nombre: "ALCICARDO",
    est_segundo_nombre: "ERIK",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP",
    est_tipo_candidato: "personero",
    est_num_tarjeton: 3,
    est_foto: "3 - Alcicardo Erik Silva.jpg"
});